main:
  - name: Home
    url: /
    weight: 10

  - name: About
    url: /about/
    weight: 20

  - name: Services
    url: /services/
    weight: 30

  - name: Portfolio
    url: /portfolio/
    weight: 40

  - name: Blog
    url: /blog/
    weight: 50

  - name: Contact
    url: /contact/
    weight: 60
