main:
  - name: Home
    url: /
    weight: 10

  - name: About
    url: /about/
    weight: 20

  - name: Services
    url: /services/
    weight: 30

  - name: Portfolio
    url: /portfolio/
    weight: 40

  - name: Resources
    url: /resources/
    weight: 50

  - name: Contact
  url: /contact/
  weight: 60

